---
title: "The vaginal microbiome and preterm birth"
author: "Hardik I Parikh"
date: "03/14/2019"
output: html_document
---

## Extended Data Figure 1

Species-level vaginal microbiome composition in women who experience term or preterm birth.  

```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(vegan)
library(dendsort)
library(ggpubr)
library(cowplot)
library(grid)
library(gridExtra)
```


#### Load Data

```{r, echo=TRUE}

# sample list for ptb47 cohort
ptb47.okpt <- read_delim("~/Documents/ptb47-extID/data/ptb47.okpt.extID.txt", delim="\t")

# read mefit stats for min 1000hq reads
mefit <- read_delim("~/Documents/ptb47-extID/data/ptb47.mefit-stats.extID.txt", delim = "\t") %>%
  filter(HQReads > 1000)

# read stirrups v2 profiles
ssdata <- read_delim("~/Documents/ptb47-extID/data/ptb47.stirrups-v2.extID.txt", delim = "\t") %>%
  filter(SampleID %in% ptb47.okpt$SampleID & 
           SampleID %in% mefit$SampleID &
           ATprop > 0.01)

# Add L.delbrueckii to EP686265_K30_MV1D
ssdata <- ssdata %>%
  rbind(c("EP686265_K30_MV1D", "Lactobacillus_delbrueckii", 0, 0.0))
ssdata$No_of_Reads <- as.numeric(ssdata$No_of_Reads)
ssdata$ATprop <- as.numeric(ssdata$ATprop)


# re-calculate proportions to 100.0
tmp <- ssdata %>%
  group_by(SampleID) %>%
  summarise(TotalReads = sum(No_of_Reads))
ssdata <- left_join(ssdata, tmp, by="SampleID") %>%
  mutate(RelAb = (No_of_Reads/TotalReads)*100)
#foo <- aggregate(ssdata$RelAb, by=list(SampleID=ssdata$SampleID), FUN=sum)

# term/preterm subjects
termstatus <- read_delim("~/Documents/ptb47-extID/data/ptb47.tags.extID.txt", delim = "\t") %>%
  filter(ParticipantID %in% ptb47.okpt$ParticipantID) %>%
  mutate(preg = ifelse(Group == "control", "term", Group))

# read custom colors
taxacolors <- read_delim("~/Documents/ptb47-extID/data/taxa_colors.txt", delim = "\t")
vtcolors <- read_delim("~/Documents/ptb47-extID/data/vt_colors.txt", delim = "\t")

```

#### Assign Vagitypes to each Sample

```{r, echo=TRUE}

### get vagitypes for each sample
### Vagitype definition: >= 30% of dominant taxa
getVagitype <- function(propData) {
  ## identify vagitypes
  vagTypes <- apply(propData, 1, which.max)
  maxProp <- propData[matrix(c(1:nrow(propData),vagTypes), ncol=2)]
  vagTypes <- colnames(propData)[vagTypes]
  vagTypes[maxProp < 30.0] <- "No Type"
  
  ## my vagTypeDF
  vagTypeDF <- data.frame(cbind(rownames(propData), vagTypes))
  vagTypeDF$vagTypes.2 <- NA
  for(i in 1:nrow(vagTypeDF)) {
    if(grepl("crispatus", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.crispatus"}
    else if(grepl("iners", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.iners"}
    else if(grepl("jensenii", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.jensenii"}
    else if(grepl("gasseri", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.gasseri"}
    else if(grepl("BVAB1", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "BVAB1"}
    else if(grepl("vaginalis", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "G.vaginalis"}
    else if(grepl("vaginae", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "A.vaginae"}
    else if(grepl("Sneathia_amnii", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "S.amnii"}
    else if(grepl("No Type", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "NoType"}
    else {vagTypeDF[i,3] <- "Other"}
  }
  
  ## set colnames
  colnames(vagTypeDF) <- c("SampleID", "vagitype", "vagitype.2") 
  
  return(vagTypeDF)
}

propData <- acast(ssdata, SampleID~Taxa, value.var = "RelAb", fill=0.0)
vagitypeDF <- getVagitype(propData)

ssdata <- left_join(ssdata, vagitypeDF, by="SampleID")
```

#### Add pregnancy status, trimester,  custom colors

```{r, echo=TRUE}
# Add pregnancy status 
ssdata <- ssdata %>%
  rowwise() %>%
  mutate(ParticipantID = strsplit(as.character(SampleID), "_")[[1]][1]) 
termstatus <- termstatus %>%
  filter(ParticipantID %in% ssdata$ParticipantID) %>%
  select(ParticipantID, preg) %>%
  unique()
ssdata <- left_join(ssdata, termstatus, by="ParticipantID") %>%
  mutate(preg = factor(preg, levels = c("term", "preterm")))

# add trimester
triDF <- ptb47.okpt %>%
  select(SampleID, trueGA, trimester)
ssdata <- left_join(ssdata, triDF, by="SampleID") %>%
  mutate(trimester = factor(trimester, levels = c("1st_tri", "2nd_tri", "3rd_tri")))


# Add custom colors
ssdata <- left_join(ssdata, taxacolors, by="Taxa") %>%
  mutate(TaxaColor = ifelse(is.na(TaxaColor), "#faf0e6", TaxaColor)) 

ssdata <- left_join(ssdata, vtcolors, by="vagitype")

```

#### Sort Samples by Vagitype

```{r, echo=TRUE}
uniq.vagitypes <- ssdata %>%
  select(vagitype.2) %>%
  unique()

# set default vagitype order
myVTOrder <- c("L.crispatus", "L.iners", "L.jensenii", "L.gasseri", "BVAB1", "G.vaginalis", "A.vaginae", "S.amnii", "Other", "NoType")

# get sample order
sampleOrder <- vector(mode="character", length=0)

for (x in myVTOrder) {
  if (x %in% uniq.vagitypes$vagitype.2) {
    ssdata_subset <- ssdata %>%
      filter(vagitype.2 == x)
    if (length(unique(ssdata_subset$SampleID)) > 1) {
      propData.subset <- acast(ssdata_subset, SampleID~Taxa, value.var = "RelAb", fill=0.0)
      bcdist <- vegdist(propData.subset, method="bray")
      hclustBC <- hclust(bcdist, method="ward.D2")
      dd <- dendsort(as.dendrogram(hclustBC))
      hclustBC.order <- as.hclust(dd)
      sampleOrder <- c(sampleOrder, hclustBC.order$labels[c(hclustBC.order$order)])
    } 
    else {
      sampleOrder <- c(sampleOrder, as.character(unique(ssdata_subset$SampleID)))
    }
  }
}

# set sample order
ssdata <- ssdata %>%
  mutate(SampleID = factor(SampleID, levels = sampleOrder)) 
ssdata$TaxaColor <- as.factor(ssdata$TaxaColor)
```

#### Stacked Bars 

```{r, echo=TRUE, fig.width=7, fig.height=7}
myStackedBarPlot <- function(inputDF) {
  p <- ggplot(inputDF, aes(SampleID, RelAb, fill=TaxaColor, group=RelAb)) + 
                geom_bar(stat = 'identity', position='stack', width = 1) +
                scale_fill_manual(values=levels(inputDF$TaxaColor)) +
                labs(y="Relative Abundance") + 
                facet_grid(preg~trimester, scales = "free_x", space = "free_x") +
                theme_bw() + 
                theme(strip.text=element_blank(),
                      axis.text.y=element_text(face="bold",size=10),
                      axis.text.x = element_blank(),
                      axis.ticks.x=element_blank(),
                      axis.title.x = element_blank(),
                      axis.title.y=element_text(face="bold", size=14),
                      legend.position = "none") 
  return(p)
}

ssdata.term <- ssdata %>%
  filter(preg == "term")
ssdata.preterm <- ssdata %>%
  filter(preg == "preterm")

# make plots
top_row <- myStackedBarPlot(ssdata.term)
bottom_row <- myStackedBarPlot(ssdata.preterm)

# get width of top_row facets, and set the bottom row facets
tr = ggplot_gtable(ggplot_build(top_row))
br = ggplot_gtable(ggplot_build(bottom_row))
br$widths[5] = tr$widths[5]
br$widths[7] = tr$widths[7]
br$widths[9] = tr$widths[9]
plot_grid(tr, br, nrow = 2)
```

```{r, echo=TRUE, fig.width=14, fig.height=3.5}

### Plot Legend
# Only show selected taxa in legend
myTaxaList <- c("Lactobacillus_crispatus_cluster", "Lactobacillus_iners", 
                "Lactobacillus_gasseri_cluster", "Lactobacillus_jensenii", 
                "Lachnospiraceae_BVAB1", "Gardnerella_vaginalis",
                "Atopobium_vaginae", "Sneathia_amnii", 
                "Lactobacillus_delbrueckii", "Prevotella_cluster2", 
                "Prevotella_bivia", 
                "Megasphaera_OTU70_type1", "Megasphaera_OTU71_type2", 
                "Clostridiales_BVAB2", 
                "Mycoplasma_hominis", "Streptococcus_cluster29", 
                "Streptococcus_agalactiae", "Mycoplasma_girerdii", 
                "Dialister_micraerophilus", "Parvimonas_OTU142",
                "Ureaplasma_cluster23", "TM7_OTU-H1" , "Aerococcus_christensenii" )
plotDF <- ssdata %>%
  filter(Taxa %in% myTaxaList) %>%
  rbind(c("EP407012_K20_MV1D","Other Taxa", 0, 0.00, 63265, 0.00, "Gardnerella_vaginalis", "G.vaginalis", "EP407012", "term", "200", "3rd_tri",  "#faf0e6", "#d62728", "red"))  #add row for Other Taxa

tmp.plot <- ggplot(plotDF, aes(SampleID, RelAb, fill=TaxaColor)) + 
  geom_bar(stat = "identity", position = "stack") + 
  theme(legend.position = "bottom", 
        legend.text = element_text(size=10),
        legend.text.align = 0,
        legend.title = element_blank(), 
        legend.justification = "center",
        plot.margin = unit(c(0, 0, 0, 0), "cm")) + 
  scale_fill_manual(values=c("#fff5aa", "#aec7e8", "#c5b0d5", 
                            "#ffbb78", "#ff7f0e", "#d62728",
                             "#c49c94", "#9467bd", "#ff9896",
                             "#1f77b4", "#17becf", "#f7b6d2", "gray60", 
                            "#dee0e5", "#98df8a", 
                             "#9edae5", "#67a9cf", "#7f7f7f", 
                             "#2ca02c", "#dbdb8d", "#bcbd22", 
                            "#e377c2", "#a5acaf", "#faf0e6"), 
                    labels=c(expression(italic("Lactobacillus crispatus")), 
                             expression(italic("Lactobacillus iners")), 
                             expression(italic("Lactobacillus gasseri")),
                             expression(italic("Lactobacillus jensenii")),
                             expression(paste(italic('"Lachnospiraceae"'), plain(" BVAB1"))), 
                             expression(italic("Gardnerella vaginalis")),
                             expression(italic("Atopobium vaginae")), 
                             expression(italic("Sneathia amnii")),
                             expression(italic("Lactobacillus delbrueckii")),
                             expression(paste(italic("Prevotella"), plain(" cluster2"))), 
                             expression(italic("Prevotella bivia")),
                             expression(paste(italic("Megasphaera"), plain(" OTU70 sp. Type1"))),
                             expression(paste(italic("Megasphaera"), plain(" OTU71 sp. Type2"))),
                             expression(paste(italic("Clostridiales"), plain(" BVAB2"))),
                             expression(italic("Mycoplasma hominis")),
                             expression(paste(italic("Streptococcus"), plain(" cluster29"))),
                             expression(italic("Streptococcus agalactiae")), 
                             expression(italic("Mycoplasma girerdii")),
                             expression(italic("Dialister micraerophilus")),
                             expression(paste(italic("Parvimonas"), plain(" OTU142"))),
                             expression(paste(italic("Ureaplasma"), plain(" cluster23"))),
                             expression(plain("TM7 OTU-H1")),
                             expression(italic("Aerococcus_christensenii")),
                             "Other Taxa")) + 
  guides(fill=guide_legend(nrow = 6))
legend <- get_legend(tmp.plot)
legend$grobs[[1]]$widths[5] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[6] <- unit(4.75, "cm")
legend$grobs[[1]]$widths[9] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[10] <- unit(5.25, "cm")
legend$grobs[[1]]$widths[13] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[14] <- unit(5.25, "cm")
legend$grobs[[1]]$widths[17] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[18] <- unit(4.75, "cm")
tlegend <- ggdraw(legend)
tlegend
```


### Ext Data Figure 2A 

```{r, echo=TRUE, fig.width=7, fig.height=7}
### Save panels individually
ggsave("~/Documents/ptb47-extID/revision-0314/figures-eps/ExtDataFigure1a_term.eps", tr, width = 10, height = 3, units = "in", dpi=600)
ggsave("~/Documents/ptb47-extID/revision-0314/figures-eps/ExtDataFigure1b_preterm.eps", br, width = 10, height = 3, units = "in", dpi=600)
ggsave("~/Documents/ptb47-extID/revision-0314/figures-eps/ExtDataFigure1_legend.eps", tlegend, width = 10, height = 1.5, units = "in", dpi=600)


#ExtDataFig1 <- plot_grid(tr, br, tlegend, nrow = 3, rel_heights = c(1.5, 1.5, 0.75))
#ExtDataFig1
#ggsave("~/Documents/ptb47-extID/revision-0314/figures/ExtDataFigure1.jpeg", ExtDataFig1, width = 10, height = 7, units = "in", dpi = 600)
```


#### Alpha Diversity

```{r, echo=TRUE}
forAlphaDiv <- acast(ssdata, SampleID~Taxa, value.var = "RelAb", fill=0.0) 

# shannon index
shannon <- as.data.frame(diversity(forAlphaDiv, index = "shannon")) %>%
  magrittr::set_colnames(c("alphadiv")) %>%
  mutate(SampleID = rownames(.)) %>%
  mutate(Index = "Shannon")
# invsim index
invsim <- as.data.frame(diversity(forAlphaDiv, index = "invsim")) %>%
  magrittr::set_colnames(c("alphadiv")) %>%
  mutate(SampleID = rownames(.)) %>%
  mutate(Index = "InvSim")

# create divDF
divDF <- bind_rows(shannon, invsim) %>%
  mutate(Index = factor(Index, levels=c("Shannon", "InvSim"))) %>%
  mutate_at("SampleID", funs(as.factor))


# add preg, trimester
mdata <- ssdata %>%
  select(SampleID, preg, trimester) %>%
  unique()
divDF <- left_join(divDF, mdata, by="SampleID")

```

#### Ext Data Figure3

```{r, echo=TRUE, fig.width=12, fig.height=4}

# Shannon Index:
divDF.shannon <- divDF %>%
  filter(Index == "Shannon")

mycomp1 <- list(c("1st_tri", "2nd_tri"), c("2nd_tri", "3rd_tri"), c("1st_tri", "3rd_tri"))
mycomp2 <- list(c("preterm", "term"))
# c("#4393c3", "#d6604d")

extdatafig3_tr_l <- ggboxplot(divDF.shannon, x="trimester", y="alphadiv", 
                        color = "preg", palette = c("#4393c3", "#d6604d"),
                        add="jitter", outlier.shape=NA) + 
  #stat_compare_means(comparisons = mycomp1, label = "p.signif") + 
  facet_grid(~preg, scales = "free_y") + 
  theme_bw() + 
  theme(axis.text.x=element_text(face="bold",size=14),
        axis.text.y=element_text(face="bold",size=12),
        axis.title=element_text(face="bold", size=16),
        legend.position = "none",
        plot.title = element_text(face="bold", size=20),
        strip.text = element_text(face = "bold", size = 16)) + 
  labs(x="Trimester", y="Alpha Diversity") + 
  ggtitle("Shannon Index")
extdatafig3_tr_r <- ggboxplot(divDF.shannon, x="preg", y="alphadiv", 
                        color = "preg", palette = c("#4393c3", "#d6604d"),
                        add="jitter", outlier.shape=NA) + 
  #stat_compare_means(comparisons = mycomp2, label = "p.signif") + 
  facet_grid(~trimester, scales = "free_y") + 
  theme_bw() + 
  theme(axis.text.x=element_text(face="bold",size=14),
        axis.text.y=element_text(face="bold",size=12),
        axis.title=element_text(face="bold", size=16),
        legend.position = "none",
        plot.title = element_text(face="bold", size=20),
        strip.text = element_text(face = "bold", size = 16)) + 
  labs(x="Pregnancy", y="") + 
  ggtitle("")

extdatafig3_tr <- plot_grid(extdatafig3_tr_l, extdatafig3_tr_r, ncol = 2, rel_widths = c(1,1))
```


```{r, fig.width=12, fig.height=4}
# InvSim Index:
divDF.invsim <- divDF %>%
  filter(Index == "InvSim")

mycomp1 <- list(c("1st_tri", "2nd_tri"), c("2nd_tri", "3rd_tri"), c("1st_tri", "3rd_tri"))
mycomp2 <- list(c("preterm", "term"))
#  c("#4393c3", "#d6604d")

extdatafig3_br_l <- ggboxplot(divDF.invsim, x="trimester", y="alphadiv", 
                        color = "preg", palette = c("#4393c3", "#d6604d"),
                        add="jitter", outlier.shape=NA) + 
  #stat_compare_means(comparisons = mycomp1, label = "p.signif") + 
  facet_grid(~preg, scales = "free_y") + 
  theme_bw() + 
  theme(axis.text.x=element_text(face="bold",size=14),
        axis.text.y=element_text(face="bold",size=12),
        axis.title=element_text(face="bold", size=16),
        legend.position = "none",
        plot.title = element_text(face="bold", size=20),
        strip.text = element_text(face = "bold", size = 16)) + 
  labs(x="Trimester", y="Alpha Diversity") + 
  ggtitle("Inverse Simpson Index")
extdatafig3_br_r <- ggboxplot(divDF.invsim, x="preg", y="alphadiv", 
                        color = "preg", palette = c("#4393c3", "#d6604d"),
                        add="jitter", outlier.shape=NA) + 
  #stat_compare_means(comparisons = mycomp2, label = "p.signif") + 
  facet_grid(~trimester, scales = "free_y") + 
  theme_bw() + 
  theme(axis.text.x=element_text(face="bold",size=14),
        axis.text.y=element_text(face="bold",size=12),
        axis.title=element_text(face="bold", size=16),
        legend.position = "none",
        plot.title = element_text(face="bold", size=20),
        strip.text = element_text(face = "bold", size = 16)) + 
  labs(x="Pregnancy", y="") + 
  ggtitle("")

extdatafig3_br <- plot_grid(extdatafig3_br_l, extdatafig3_br_r, ncol = 2, rel_widths = c(1,1))
```


```{r, echo=TRUE, fig.width=12, fig.height=8}
ExtDataFig3 <- plot_grid(extdatafig3_tr, extdatafig3_br, nrow = 2)
ExtDataFig3 
```


