---
title: "The vaginal microbiome and preterm birth"
author: "Hardik I Parikh"
date: "03/14/2019"
output: html_document
---

## Extended Data: Figure 2

Alpha diversity measures for the cross-sectional cohort shown in Figure 2A

```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(vegan)
library(ggpubr)
```


#### Load Data

```{r, echo=TRUE}

# sample list for ptb47 cohort
ptb45 <- read_delim("sample_list.txt", delim="\t")

# read stirrups v2 profiles
ssdata <- read_delim("stirrups_profiles.txt", delim = "\t") %>%
  filter(SampleID %in% ptb45$SampleID)

# re-calculate proportions to 100.0
tmp <- ssdata %>%
  group_by(SampleID) %>%
  summarise(TotalReads = sum(No_of_Reads))
ssdata <- left_join(ssdata, tmp, by="SampleID") %>%
  mutate(RelAb = (No_of_Reads/TotalReads)*100)
#foo <- aggregate(ssdata$RelAb, by=list(SampleID=ssdata$SampleID), FUN=sum)

# term/preterm subjects
termstatus <- read_delim("metadata.txt", delim = "\t") %>%
  filter(ParticipantID %in% ptb45$PID) %>%
  mutate(preg = ifelse(Group == "control", "term", Group))

```

#### Calculate Alpha Diversity

```{r, echo=TRUE}
forAlphaDiv <- acast(ssdata, SampleID~Taxa, value.var = "RelAb", fill=0.0) 

# shannon index
shannon <- as.data.frame(diversity(forAlphaDiv, index = "shannon")) %>%
  magrittr::set_colnames(c("alphadiv")) %>%
  mutate(SampleID = rownames(.)) %>%
  mutate(Index = "Shannon")
# invsim index
invsim <- as.data.frame(diversity(forAlphaDiv, index = "invsim")) %>%
  magrittr::set_colnames(c("alphadiv")) %>%
  mutate(SampleID = rownames(.)) %>%
  mutate(Index = "Inverse Simpson")

# create divDF
divDF <- bind_rows(shannon, invsim) %>%
  mutate(Index = factor(Index, levels=c("Shannon", "Inverse Simpson"))) %>%
  mutate_at("SampleID", funs(as.factor))
```

#### Add pregnancy status

```{r, echo=TRUE}
# Add pregnancy status 
divDF <- divDF %>%
  rowwise() %>%
  mutate(ParticipantID = strsplit(as.character(SampleID), "_")[[1]][1]) 

termstatus <- termstatus %>%
  filter(ParticipantID %in% divDF$ParticipantID) %>%
  select(ParticipantID, preg) %>%
  unique()

divDF <- left_join(divDF, termstatus, by="ParticipantID") %>%
  mutate(preg = factor(preg, levels = c("term", "preterm")))


```

### Figure  

```{r, echo=TRUE, fig.width=7, fig.height=5}

mycomp <- list(c("preterm", "term"))

ggboxplot(divDF, x="preg", y="alphadiv", color = "preg", palette = c("#4393c3", "#d6604d"),
          add="jitter", outlier.shape=NA) + 
  stat_compare_means(comparisons = mycomp, label = "p.signif") + 
  facet_wrap(~Index, scales = "free_y") + 
  theme_bw() + 
  theme(axis.text.x=element_text(face="bold",size=14),
        axis.text.y=element_text(face="bold",size=12),
        axis.title=element_text(face="bold", size=16),
        legend.position = "none",
        plot.title = element_text(face="bold", size=20),
        strip.text = element_blank()) + 
  labs(x="Pregnancy", y="Alpha Diversity")

ggsave("ExtDataFigure2a.eps", width = 7, height = 4.5, units = "in", dpi=600)
```

