---
title: "The vaginal microbiome and preterm birth"
author: "Hardik I Parikh"
date: "03/14/2019"
output: html_document
---

## Figure 1A

TB / PTB Radial plots (ptb45 - cohort)

```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(vegan)
library(dendsort)
library(cowplot)
library(gridExtra)
```


#### Load Data

```{r, echo=TRUE}

# sample list for ptb47 cohort
ptb45 <- read_delim("~/Documents/ptb47-extID/data/ptb47.edupugantil-firstVisit.extID.txt", delim="\t")

# read stirrups v2 profiles
ssdata <- read_delim("~/Documents/ptb47-extID/data/ptb47.stirrups-v2.extID.txt", delim = "\t") %>%
  filter(SampleID %in% ptb45$SampleID)

# re-calculate proportions to 100.0
tmp <- ssdata %>%
  group_by(SampleID) %>%
  summarise(TotalReads = sum(No_of_Reads))
ssdata <- left_join(ssdata, tmp, by="SampleID") %>%
  mutate(RelAb = (No_of_Reads/TotalReads)*100)
#foo <- aggregate(ssdata$RelAb, by=list(SampleID=ssdata$SampleID), FUN=sum)

# term/preterm subjects
termstatus <- read_delim("~/Documents/ptb47-extID/data/ptb47.tags.extID.txt", delim = "\t") %>%
  filter(ParticipantID %in% ptb45$PID) %>%
  mutate(preg = ifelse(Group == "control", "term", Group))

# read custom colors
taxacolors <- read_delim("~/Documents/ptb47-extID/data/taxa_colors.txt", delim = "\t")
vtcolors <- read_delim("~/Documents/ptb47-extID/data/vt_colors.txt", delim = "\t")

```

#### Assign Vagitypes to each Sample

```{r, echo=TRUE}

### get vagitypes for each sample
### Vagitype definition: >= 30% of dominant taxa
getVagitype <- function(propData) {
  ## identify vagitypes
  vagTypes <- apply(propData, 1, which.max)
  maxProp <- propData[matrix(c(1:nrow(propData),vagTypes), ncol=2)]
  vagTypes <- colnames(propData)[vagTypes]
  vagTypes[maxProp < 30.0] <- "No Type"
  
  ## my vagTypeDF
  vagTypeDF <- data.frame(cbind(rownames(propData), vagTypes))
  vagTypeDF$vagTypes.2 <- NA
  for(i in 1:nrow(vagTypeDF)) {
    if(grepl("crispatus", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.crispatus"}
    else if(grepl("iners", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.iners"}
    else if(grepl("jensenii", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.jensenii"}
    else if(grepl("gasseri", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "L.gasseri"}
    else if(grepl("BVAB1", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "BVAB1"}
    else if(grepl("vaginalis", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "G.vaginalis"}
    else if(grepl("vaginae", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "A.vaginae"}
    else if(grepl("Sneathia_amnii", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "S.amnii"}
    else if(grepl("No Type", vagTypeDF[i,2])) {vagTypeDF[i,3] <- "NoType"}
    else {vagTypeDF[i,3] <- "Other"}
  }
  
  ## set colnames
  colnames(vagTypeDF) <- c("SampleID", "vagitype", "vagitype.2") 
  
  return(vagTypeDF)
}

propData <- acast(ssdata, SampleID~Taxa, value.var = "RelAb", fill=0.0)
vagitypeDF <- getVagitype(propData)

ssdata <- left_join(ssdata, vagitypeDF, by="SampleID")
```

#### Add pregnancy status, custom colors

```{r, echo=TRUE}
# Add pregnancy status 
ssdata <- ssdata %>%
  rowwise() %>%
  mutate(ParticipantID = strsplit(as.character(SampleID), "_")[[1]][1]) 

termstatus <- termstatus %>%
  filter(ParticipantID %in% ssdata$ParticipantID) %>%
  select(ParticipantID, preg) %>%
  unique()

ssdata <- left_join(ssdata, termstatus, by="ParticipantID")

# Add custom colors
ssdata <- left_join(ssdata, taxacolors, by="Taxa") %>%
  mutate(TaxaColor = ifelse(is.na(TaxaColor), "#faf0e6", TaxaColor)) 

ssdata <- left_join(ssdata, vtcolors, by="vagitype")

```

#### Sort Samples by Vagitype

```{r, echo=TRUE}
uniq.vagitypes <- ssdata %>%
  select(vagitype.2) %>%
  unique()

# set default vagitype order
myVTOrder <- c("L.crispatus", "L.iners", "L.jensenii", "L.gasseri", "BVAB1", "G.vaginalis", "A.vaginae", "S.amnii", "Other", "NoType")

# get sample order
sampleOrder <- vector(mode="character", length=0)

for (x in myVTOrder) {
  if (x %in% uniq.vagitypes$vagitype.2) {
    ssdata_subset <- ssdata %>%
      filter(vagitype.2 == x)
    if (length(unique(ssdata_subset$SampleID)) > 1) {
      propData.subset <- acast(ssdata_subset, SampleID~Taxa, value.var = "RelAb", fill=0.0)
      bcdist <- vegdist(propData.subset, method="bray")
      hclustBC <- hclust(bcdist, method="ward.D2")
      dd <- dendsort(as.dendrogram(hclustBC))
      hclustBC.order <- as.hclust(dd)
      sampleOrder <- c(sampleOrder, hclustBC.order$labels[c(hclustBC.order$order)])
    } 
    else {
      sampleOrder <- c(sampleOrder, as.character(unique(ssdata_subset$SampleID)))
    }
  }
}

# set sample order
ssdata <- ssdata %>%
  mutate(SampleID = factor(SampleID, levels = sampleOrder)) 
ssdata$TaxaColor <- as.factor(ssdata$TaxaColor)
```

#### Radial Plot 

```{r, echo=TRUE}
myRadialStackedBarPlot <- function(inputDF) {
  p <- ggplot(inputDF, aes(SampleID, RelAb, fill=TaxaColor, group=RelAb)) + 
                geom_bar(stat = 'identity', position='stack') +
                scale_fill_manual(values=levels(inputDF$TaxaColor)) +
                coord_polar() +
                labs(x="Sample", y="Relative Abundance") + 
                theme(axis.text=element_blank(), 
                      axis.ticks=element_blank(), 
                      axis.title=element_blank(), 
                      legend.position = "none", 
                      panel.grid=element_blank(),
                      panel.border = element_blank(),
                      panel.background = element_rect(fill="transparent", color=NA),
                      plot.background = element_rect(fill="transparent", color=NA),
                      axis.line = element_blank()) +
                ylim(-50, 100)
  return(p)
}

```

#### Donut Plot

```{r, echo=TRUE}
# Write the function again ... 
### AAARRRRGGGGHHHH !!!

myDonutPlot <- function(inputDF) {
  
  myVagitypeOrder <- c("Lactobacillus_crispatus_cluster", "Lactobacillus_iners", "Lactobacillus_gasseri_cluster", 
                       "Lachnospiraceae_BVAB1", "Gardnerella_vaginalis", "Atopobium_vaginae", 
                       "Sneathia_amnii", "Lactobacillus_delbrueckii", "Prevotella_cluster2",
                       "Streptococcus_agalactiae", "Streptococcus_cluster29", "Mycoplasma_girerdii", 
                       "No Type")

  donut.tbl <- inputDF %>%
    select(SampleID, vagitype) %>%
    unique() %>%
    count(vagitype) %>%
    mutate(vagitype = factor(vagitype, levels = myVagitypeOrder)) %>%
    arrange(vagitype) %>%
    mutate(fraction = n / sum(n)) %>%
    mutate(ymax = cumsum(fraction)) %>%
    mutate(ymin = c(0, head(ymax, n=-1))) %>%
    left_join(., vtcolors, by="vagitype") %>%
    mutate(vagitype = factor(vagitype, levels = myVagitypeOrder))
  
  p <- ggplot(donut.tbl, aes(fill=vagitype, ymax=ymax, ymin=ymin, xmax=7, xmin=6.5)) +
        geom_rect(colour="white") +
        coord_polar(theta="y") +
        xlim(c(0, 7)) + 
        scale_fill_manual(values = donut.tbl$VTColor) +
        theme(panel.grid=element_blank(),
              panel.border=element_blank(),
              panel.background = element_rect(fill="transparent", color=NA),
              plot.background = element_rect(fill="transparent", color=NA),
              axis.text=element_blank(), 
              axis.ticks=element_blank(), 
              legend.position = "none",
              axis.line = element_blank()) 
  
  return(p)
}

```

### Figure 1A 

```{r, echo=TRUE, fig.width=7, fig.height=7}

### Figure 1A 
### Term pregnancies 
ssdata.term <- ssdata %>%
  filter(preg == "term")
radial <- myRadialStackedBarPlot(ssdata.term)
donut <- myDonutPlot(ssdata.term)
fig1a <- ggdraw() + 
  draw_plot(radial, 0, 0, 1, 1, 0.875) + 
  draw_plot(donut, 0, 0, 1, 1) + 
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

### Figure 1B 
### Preterm pregnancies 
ssdata.preterm <- ssdata %>%
  filter(preg == "preterm")
radial <- myRadialStackedBarPlot(ssdata.preterm)
donut <- myDonutPlot(ssdata.preterm)
fig1b <- ggdraw() + 
  draw_plot(radial, 0, 0, 1, 1, 0.875) + 
  draw_plot(donut, 0, 0, 1, 1) + 
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
```

```{r, echo=TRUE, fig.width=14, fig.height=3.5}

### Plot Legend
# Only show selected taxa in legend
myTaxaList <- c("Lactobacillus_crispatus_cluster", "Lactobacillus_iners", "Lactobacillus_gasseri_cluster",
                "Lactobacillus_jensenii", "Lachnospiraceae_BVAB1", "Gardnerella_vaginalis",
                "Atopobium_vaginae", "Sneathia_amnii", "Lactobacillus_delbrueckii",
                "Prevotella_cluster2", "Megasphaera_OTU70_type1", "Mycoplasma_hominis",
                "Streptococcus_cluster29", "Streptococcus_agalactiae", "Mycoplasma_girerdii", 
                "Ureaplasma_cluster23")
plotDF <- ssdata %>%
  filter(Taxa %in% myTaxaList) %>%
  rbind(c("EP407012_K20_MV1D","Other Taxa", 0, 0.00, 63265, 0.00, "Gardnerella_vaginalis", "G.vaginalis", "EP407012", "term", "#faf0e6", "#d62728", "red"))  #add row for Other Taxa

tmp.plot <- ggplot(plotDF, aes(SampleID, RelAb, fill=TaxaColor, group=RelAb)) + 
  geom_bar(stat = "identity", position = "stack") + 
  theme(legend.position = "bottom", 
        legend.text = element_text(size=10),
        legend.text.align = 0,
        legend.title = element_blank(), 
        legend.justification = "center",
        plot.margin = unit(c(0, 0, 0, 0), "cm")) + 
  scale_fill_manual(values=c("#fff5aa", "#aec7e8", "#c5b0d5", 
                            "#ffbb78", "#ff7f0e", "#d62728",
                             "#c49c94", "#9467bd", "#ff9896",
                             "#1f77b4", "#f7b6d2", "#98df8a", 
                             "#9edae5", "#67a9cf", "#7f7f7f", 
                             "#2ca02c", "#faf0e6"), 
                    labels=c(expression(italic("Lactobacillus crispatus")), 
                             expression(italic("Lactobacillus iners")), 
                             expression(italic("Lactobacillus gasseri")),
                             expression(italic("Lactobacillus jensenii")),
                             expression(paste(italic('"Lachnospiraceae"'), plain(" BVAB1"))), 
                             expression(italic("Gardnerella vaginalis")),
                             expression(italic("Atopobium vaginae")), 
                             expression(italic("Sneathia amnii")),
                             expression(italic("Lactobacillus delbrueckii")),
                             expression(paste(italic("Prevotella"), plain(" cluster2"))), 
                             expression(paste(italic("Megasphaera"), plain(" OTU70 sp. Type1"))),
                             expression(italic("Mycoplasma hominis")),
                             expression(paste(italic("Streptococcus"), plain(" cluster29"))),
                             expression(italic("Streptococcus agalactiae")), 
                             expression(italic("Mycoplasma girerdii")),
                             expression(paste(italic("Ureaplasma"), plain(" cluster23"))), "Other Taxa")) + 
  guides(fill=guide_legend(nrow = 6))
legend <- get_legend(tmp.plot)
legend$grobs[[1]]$widths[5] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[6] <- unit(4.75, "cm")
legend$grobs[[1]]$widths[9] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[10] <- unit(5.25, "cm")
legend$grobs[[1]]$widths[13] <- unit(0.25, "cm")
legend$grobs[[1]]$widths[14] <- unit(4.75, "cm")
tlegend <- ggdraw(legend)
#tlegend

```


```{r, echo=TRUE, fig.width=7, fig.height=5.5}
### Combine into one figure
top_row <- plot_grid(fig1a, fig1b)
ggsave("~/Documents/ptb47-extID/revision-0314/figures-eps/Figure2A.eps", top_row, units = "in", width = 7, height = 4, dpi=600)
ggsave("~/Documents/ptb47-extID/revision-0314/figures-eps/Figure2A_legend.eps", tlegend, units = "in", width = 7, height = 1.5, dpi=600)
#top_row <- plot_grid(fig1a, fig1b)
#plot_grid(top_row, tlegend, nrow = 2, rel_heights = c(2.5, 1), align = "v")
#ggsave("~/Documents/ptb47-extID/revision-0314/figures/Figure1A.jpeg", width = 7, height = 4, units = "in", dpi = 600)
```
