---
title: "PTB Figures 3, 5, and Supplemental Data Figure 1"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE}
library(knitr)
```


```{r warning=FALSE, message=FALSE, echo=FALSE}
set.seed(12345)

library("reshape2")
library("dplyr")
library("tidyr")
```

```{r echo=FALSE}
#Read mapping file.
mappingData <- read.table(paste(pathToData, mappingFile, sep=""), 
                      header=T, sep="\t")
  
subjectType <- rep(NA, nrow(mappingData))
subjectType[grep("M.",mappingData$SampleType)] <- "Mom"
subjectType[grep("B.",mappingData$SampleType)] <- "Baby"
mappingData <- data.frame(mappingData,subjectType)

mappingData <- mappingData %>%
                  mutate(BodySite=ifelse(mappingData$subjectType=="Baby",
                  paste(BodySite,"Baby",sep=""),
                  as.character(BodySite)))
mappingData$BodySite <- as.factor(mappingData$BodySite)
```


```{r echo=FALSE}
#Read 16S data and keep AT reads only.  Merge with mapping file.
data16S <- read.table(paste(pathToData, file16S_stirrups, sep=""), 
		      header=T, sep="\t")
data16S <- data16S[data16S$Threshold.Status=="AT",]
data16S <- merge(data16S, mappingData)
data16S <- dcast(data16S, SampleID + KitID + ParticipantID + VisitNum + BodySite + 
                          subjectType ~ Taxa, value.var="No_of_Reads", fill = 0)
taxaCols <- 7:ncol(data16S)
```

```{r echo=FALSE, warning=FALSE}
#Read clinical data.
clinData <- read.table(paste(pathToData, clinFile, sep=""), header=TRUE, sep="\t")
clinDcast <- dcast(clinData, PID + kitId ~ VariableName, value.var="Value") 
clinDcast <- merge(clinDcast, mappingData, by.x="kitId", by.y="KitID")

myClinData <- data.frame(lapply(clinDcast, # the data.frame function will create factors from other variables
    function(x) {
                   # try converting to numeric first
                   
                 if ((class(x) != "factor") & (sum(is.na(x)) == 
					       sum(is.na(as.numeric(x))))) {
                     as.numeric(x)
                 }else {
                     as.character(x)
                 }
               }
       ))

#Trimesters defined at 13 and 27 weeks.
trimester <- rep(NA, nrow(myClinData))
trimester[!is.na(myClinData$true_ga) & myClinData$true_ga >= 0 
	         & myClinData$true_ga < 13*7] <- "1"
trimester[!is.na(myClinData$true_ga) & myClinData$true_ga >= 13*7  & 
            myClinData$true_ga < 27*7] <- "2"
trimester[!is.na(myClinData$true_ga) & myClinData$true_ga >= 27*7  & 
          !is.na(myClinData$days_rel2birth) & myClinData$days_rel2birth < 0] <- "3" 
trimester[(myClinData$days_rel2birth == 0) &
	  (grepl("^B", myClinData$SampleType))] <- "Baby Delivery"
trimester[(myClinData$days_rel2birth > 0) & 
	  (grepl("^B", myClinData$SampleType))] <- "Baby Discharge"
trimester[(myClinData$days_rel2birth == 0) & 
	  (grepl("^M", myClinData$SampleType))] <- "Mom Delivery"
trimester[(myClinData$days_rel2birth > 0) & 
	  (grepl("^M", myClinData$SampleType))] <- "Mom Discharge"
trimester <- factor(trimester)

myClinData <- myClinData %>%
                mutate(height=ifelse(height < 42 | height > 90, NA, height)) %>%
                mutate(weight=ifelse(subjectType=="Baby", weight/16, ifelse(weight < 800, weight, weight/16))) %>%
                mutate(weight=ifelse(weight==0, NA, ifelse(weight > 40 & weight < 80, NA, weight))) %>%
                mutate(bmi=weight/height/height*703)
  
myClinData <- data.frame(myClinData, trimester)
myClinData <- myClinData[!is.na(myClinData$trimester),]
```


Read cytokine data.  
```{r}
cytokines <- read.table(paste(pathToCytokines,
  		      cytokineFile,sep=""), header=T, sep="\t", 
                      colClasses = c(rep("factor",3),rep("character",2), rep("numeric", 2), 
                      "numeric", "character"), na.strings=c("ND", "N/A"))

cytokines <- merge(cytokines, mappingData)

myCytoList <- c("IL-1b", "Eotaxin", "IL-8", "TNF-a", "IL-17A", "MIP-1b", "IL-6", "IP-10", "RANTES")

cytokines <- cytokines %>%
               filter(Cytokine %in% myCytoList)

cytoDcast <- dcast(cytokines, SampleID + KitID + ParticipantID + VisitNum + BodySite ~ 
                              Cytokine, value.var = "Imputed.CytokineConc.round2.pg.ml.")
cytoDcast <- cytoDcast[apply(is.na(cytoDcast[,6:ncol(cytoDcast)]),1,sum) != 
                                                                 ncol(cytoDcast)-5,]
cytoDcast[,6:ncol(cytoDcast)] <- log(cytoDcast[,6:ncol(cytoDcast)])

#merge cytokine data with clinical data
cytoDcast <- merge(cytoDcast, myClinData[,c("SampleID", "kitId", "true_ga", "PID", "VisitNum", "trimester")], 
                      by.x=c("SampleID", "KitID", "ParticipantID", "VisitNum"), by.y=c("SampleID", "kitId", "PID", "VisitNum"))

```


```{r warning=FALSE, echo=FALSE}
#Read survey data.  
surveyData <- read.table(paste(pathToData, surveyFile, sep=""), header=TRUE, sep="\t")
surveyDcast <- dcast(surveyData, SubjectID + KitID + Category + CategoryShort ~ VariableName, value.var="Value") 
mySurveyData <- data.frame(lapply(surveyDcast, 
    function(x) {
                   # try converting to numeric first
                   if ((class(x) != "factor") & 
                       (sum(is.na(x)) == sum(is.na(as.numeric(x))))) {
                     as.numeric(x)
                   }   
                   else {
                     as.character(x)
                   }
                 }
       ))
```

```{r echo=FALSE}
#Read medical abstraction data.
medicalData <- read.table(paste(pathToData, medicalFile, sep=""), 
			  header=TRUE, sep="\t")
```

```{r echo=FALSE}
# At least 1,000 read
totalcounts <- apply(data16S[,taxaCols],1,sum)
data16S <- data16S %>%
  filter(totalcounts >= 1000) %>%
  dplyr::select(SampleID, KitID, ParticipantID, VisitNum, BodySite, subjectType, which(apply(data16S[,taxaCols],2,function(x) {sum(x!=0)>=10}))+6)

taxaCols <- 7:ncol(data16S)

#Convert to proportions.
totalcounts <- apply(data16S[,taxaCols],1,sum)
prop16S <- data16S
prop16S[,taxaCols] <- data16S[,taxaCols]/totalcounts

# Mom samples only
prop16S <- prop16S %>%
  filter(substr(SampleID,1,4) == "MV1D" | substr(SampleID,1,4) == "MCKD" | substr(SampleID,1,4) == "MRCD" )

# visit number as integer
prop16S$VisitNum <- as.integer(as.character(prop16S$VisitNum))
```

```{r echo=FALSE}
#Calculate diversity.
prop16S <- prop16S %>%
  mutate(alphaDiv = 1/rowSums(.[,taxaCols]^2)) 

# add vagitype
mypropdata <- prop16S[,taxaCols]
mytypes <- apply(mypropdata,1,which.max)
maxprop <- as.numeric(mypropdata[matrix(c(1:nrow(mypropdata),mytypes), ncol=2)])
mytypes <- colnames(mypropdata)[mytypes]
mytypes[maxprop < 0.3] <- "No Type"
mytypes <- as.factor(mytypes)
prop16S <- prop16S %>%
  mutate(vagitype=mytypes)

#Convert to log transformation
prop16S[,taxaCols] <- prop16S[,taxaCols]-0.001
prop16S[,taxaCols][prop16S[,taxaCols] < 0] <- 0

#Renormalize
prop16S[,taxaCols] <- prop16S[,taxaCols]/apply(prop16S[,taxaCols],1,sum)

prop16S[,taxaCols] <- log10((prop16S[,taxaCols] + 0.001)/0.001)

```

```{r, echo=FALSE}
#Add Ethnicity
AfricanAmerican <- as.character(
                 unique(mySurveyData$SubjectID[
                                     !is.na(mySurveyData$african_american) &
                                     mySurveyData$african_american == "Yes" & 
                                     mySurveyData$caucasian == "No" & 
                                     mySurveyData$american_indian_or_alaska_native == "No" & 
                                     mySurveyData$asian == "No" & 
                                     mySurveyData$hispanic_or_latino =="No" &
                                     mySurveyData$native_hawaiian == "No"]))
Caucasian <- as.character(
                unique(mySurveyData$SubjectID[
                                     !is.na(mySurveyData$caucasian) &
                                     mySurveyData$african_american == "No" & 
                                     mySurveyData$caucasian == "Yes" & 
                                     mySurveyData$american_indian_or_alaska_native == "No" & 
                                     mySurveyData$asian == "No" & 
                                     mySurveyData$hispanic_or_latino =="No" &
                                     mySurveyData$native_hawaiian == "No"]))
Asian <- as.character(
                unique(mySurveyData$SubjectID[
                                     !is.na(mySurveyData$asian) &
                                     mySurveyData$african_american == "No" & 
                                     mySurveyData$caucasian == "No" & 
                                     mySurveyData$american_indian_or_alaska_native == "No" & 
                                     mySurveyData$asian == "Yes" & 
                                     mySurveyData$hispanic_or_latino =="No" &
                                     mySurveyData$native_hawaiian == "No"]))

AIorAN <- as.character(
                unique(mySurveyData$SubjectID[
                                     !is.na(mySurveyData$american_indian_or_alaska_native) &
                                     mySurveyData$african_american == "No" & 
                                     mySurveyData$caucasian == "No" & 
                                     mySurveyData$american_indian_or_alaska_native == "Yes" & 
                                     mySurveyData$asian == "No" & 
                                     mySurveyData$hispanic_or_latino =="No" &
                                     mySurveyData$native_hawaiian == "No"]))

Hawaiian <- as.character(
                unique(mySurveyData$SubjectID[
                                     !is.na(mySurveyData$native_hawaiian) &
                                     mySurveyData$african_american == "No" & 
                                     mySurveyData$caucasian == "No" & 
                                     mySurveyData$american_indian_or_alaska_native == "No" & 
                                     mySurveyData$asian == "No" & 
                                     mySurveyData$hispanic_or_latino =="No" &
                                     mySurveyData$native_hawaiian == "Yes"]))

Hispanic <- as.character(
                unique(mySurveyData$SubjectID[
                                     !is.na(mySurveyData$hispanic_or_latino) &
                                     mySurveyData$african_american == "No" & 
                                     mySurveyData$caucasian == "No" & 
                                     mySurveyData$american_indian_or_alaska_native == "No" & 
                                     mySurveyData$asian == "No" & 
                                     mySurveyData$native_hawaiian == "No" &
                                     mySurveyData$hispanic_or_latino =="Yes"]))

prop16S$ethnicity[prop16S$ParticipantID %in% AfricanAmerican] <- "AfricanAmerican"
prop16S$ethnicity[prop16S$ParticipantID %in% Caucasian] <- "Caucasian"
prop16S$ethnicity[prop16S$ParticipantID %in% Asian] <- "Asian"
prop16S$ethnicity[prop16S$ParticipantID %in% Hawaiian] <- "Hawaiian"
prop16S$ethnicity[prop16S$ParticipantID %in% Hispanic] <- "Hispanic"

prop16S$ethnicity2 <- prop16S$ethnicity
prop16S$ethnicity2[prop16S$ethnicity2 != "AfricanAmerican"] <- "Other"

prop16S <- prop16S[,c(1:6, 256:259, 7:255) ]

```


```{r echo=FALSE}
#Calculate pre-term versus full-term.
medicalData$ptft <- factor(ifelse(medicalData$ga_at_delivery.days. < 273, "pt", "ft"), levels=c("ft", "pt"))

ptft16S <- merge(medicalData[,c("PID", "ptft", "ga_at_delivery.days.")], prop16S, by.x="PID", by.y="ParticipantID")

# add trimester
ptft16S <- merge(myClinData[,c("SampleID", "trimester", "true_ga", "vaginal_ph" , "bmi")], ptft16S, by="SampleID")

#add pt/ft back to prop16S data 
prop16S <- ptft16S

# add BV-associated bacteria
ptft16S <- ptft16S %>%
  mutate(BVAssociated = rowSums(.[c(grep("Ureaplasma", names(.)), 
				    #grep("BVAB1", names(.)),
                                    grep("Fusobacterium", names(.)), grep("Leptotrichia", names(.)), 
                                    #grep("Gardnerella", names(.)), 
				    #grep("Sneathia", names(.)), 
                                    grep("Mycoplasma", names(.)),
                                    grep("Prevotella", names(.)),
                                    grep("BVAB2", names(.)),
                                    grep("BVAB3", names(.)), grep("Atopobium", names(.)), 
                                    grep("Mobiluncus", names(.)), grep("Megasphaera", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Megasphaera = rowSums(.[c(grep("Megasphaera", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Lcrispatus = rowSums(.[c(grep("crispatus", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Liners = rowSums(.[c(grep("iners", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Lgasseri = rowSums(.[c(grep("gasseri", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Gvaginalis = rowSums(.[c(grep("Gardnerella", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(BVAB1 = rowSums(.[c(grep("BVAB1", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Sneathia_amnii = rowSums(.[c(grep("Sneathia_amnii", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Sneathia_sanguinegens = rowSums(.[c(grep("Sneathia_sanguinegens", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Prevotella_amnii = rowSums(.[c(grep("Prevotella_amnii", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Prevotella_cluster2 = rowSums(.[c(grep("Prevotella_cluster2", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(Avaginae = rowSums(.[c(grep("Atopobium", names(.)))]))
ptft16S <- ptft16S %>%
  mutate(TM7 = rowSums(.[c(grep("TM7_OTU-H1", names(.)))]))

```

```{r echo=FALSE}
ptft16S <- ptft16S %>%
  dplyr::select(PID, KitID,trimester, ptft, ga_at_delivery.days., VisitNum, vagitype, true_ga,	vaginal_ph, bmi, ethnicity, ethnicity2,BodySite, Sneathia_amnii,                  Prevotella_amnii, Prevotella_cluster2, BVAB1, Lcrispatus, Gvaginalis, Avaginae, TM7, Liners)

ptft16S <- ptft16S %>%
             arrange(PID,KitID)

 cyto16S <- merge(cytoDcast,ptft16S,by.x=c("KitID", "ParticipantID","VisitNum","true_ga", "trimester"),by.y=c("KitID", "PID", "VisitNum","true_ga","trimester"))
 colnames(cyto16S)[9] <- "IL17A"
 colnames(cyto16S)[10] <- "IL1b"
 colnames(cyto16S)[11] <- "IL6"
 colnames(cyto16S)[12] <- "IL8"
 colnames(cyto16S)[13] <- "IP10"
 colnames(cyto16S)[14] <- "MIP1b"
 colnames(cyto16S)[16] <- "TNFa"
 
 cyto16S_gamm <- cyto16S %>%
   arrange(ParticipantID) %>%
   droplevels()

```



# Plot of Taxa over time by preterm/fullterm and ethnicity (Figure 3 and Supplemental Data Figure 1)
```{r echo=FALSE}
library(ggplot2)

geeDF <- ptft16S %>%
  mutate(ptft01=as.integer(ptft)-1) %>%
  filter(!is.na(ethnicity2)) %>%
  arrange(PID) %>%
  droplevels()
  
taxa_names <- c("Sneathia_amnii" = "S. amnii",
                "Prevotella_cluster2" = "Prevotella cluster 2",
                "Prevotella_amnii" = "P. amnii",
                "BVAB1" = "BVAB1",
                "Lcrispatus" = "L. crispatus",
                "Gvaginalis" = "G. vaginalis",
                "Avaginae" = "A. vaginae",
                "TM7" = "TM7 - H1",
                "Liners" = "L. iners")

#Plot for AA vs. Other
plotDF <- melt(geeDF,id=c("KitID", "BodySite", "ptft", "PID", "true_ga", "vagitype", "bmi", "vaginal_ph","ethnicity", "ethnicity2","ptft01", "trimester",                                  "ga_at_delivery.days.", "VisitNum")) 

plotDF <- plotDF %>%
            filter(!is.na(ethnicity2))

plotDF$ptft <- factor(plotDF$ptft, levels=c("pt","ft"), labels=c("Preterm","Full Term"))
plotDF$ethnicity2 <- factor(plotDF$ethnicity2, levels=c("AfricanAmerican","Other"), labels=c("AA","Other"))


#Overall PT/FT (AA vs. Other)
r <- ggplot(data=plotDF, aes(x=true_ga, y=as.numeric(value), group=PID, colour=ptft))  + 
  scale_color_manual(values=c("#b2182b","#4393c3","#67001f","#2166ac")) 
  

r + facet_wrap(~ variable, ncol=3,labeller = as_labeller(taxa_names)) + stat_smooth(method="gam", formula = y~s(x),
    aes(group=ptft), se= TRUE, size=1.2) +  theme(legend.position=c(0.51,0.21),legend.margin=margin(t=0,r=0,b=0,l=0,unit="cm")) + 
    labs(colour=NULL, x="Gestational Age", y="log(Relative Abundance)")

#Plot for Overall PT/FT (include points)
s <- ggplot(data=plotDF, aes(x=true_ga, y=as.numeric(value), group=PID, colour=ptft))  + geom_point() + geom_line() + 
  scale_color_manual(values=c("#b2182b","#4393c3","#67001f","#2166ac")) 
  

s + facet_wrap(~ variable, ncol=3,labeller = as_labeller(taxa_names)) + stat_smooth(method="gam", formula = y~s(x),
    aes(group=ptft), se= TRUE,  size=1.2) +   
    labs(colour=NULL, x="Gestational Age", y="log(Relative Abundance)")
  


#Plot for AA vs. EA
plotDF <- melt(geeDF,id=c("KitID", "BodySite", "ptft", "PID", "true_ga", "vagitype", "bmi", "vaginal_ph","ethnicity", "ethnicity2","ptft01", "trimester",                                   "ga_at_delivery.days.", "VisitNum")) 

plotDF <- plotDF %>%
            filter(ethnicity=="Caucasian" | ethnicity=="AfricanAmerican") 

plotDF$ptft <- factor(plotDF$ptft, levels=c("pt","ft"), labels=c("Preterm","Full Term"))
plotDF$ethnicity <- factor(plotDF$ethnicity, levels=c("AfricanAmerican","Caucasian"), labels=c("AA","EA"))

t <- ggplot(data=plotDF, aes(x=true_ga, y=as.numeric(value), group=PID, colour=interaction(ptft,ethnicity,sep=" ")))  + 
  scale_color_manual(values=c("#b2182b","#4393c3","#67001f","#2166ac")) 
  

t + facet_wrap(~ variable, ncol=3,labeller = as_labeller(taxa_names)) + stat_smooth(method="gam", formula = y~s(x),
    aes(group=interaction(ptft,ethnicity)), se= TRUE, size=1.2) +  theme(legend.position=c(0.51,0.21),legend.margin=margin(t=0,r=0,b=0,l=0,unit="cm")) + 
    labs(colour=NULL, x="Gestational Age", y="log(Relative Abundance)")

#Plot for AA vs. EA (include points)
u <- ggplot(data=plotDF, aes(x=true_ga, y=as.numeric(value), group=PID, colour=interaction(ptft,ethnicity,sep=" ")))  + geom_point() + geom_line() + 
  scale_color_manual(values=c("#b2182b","#4393c3","#67001f","#2166ac")) 
  

u + facet_wrap(~ variable, ncol=3,labeller = as_labeller(taxa_names)) + stat_smooth(method="gam", formula = y~s(x),
    aes(group=interaction(ptft,ethnicity)), se= TRUE,  size=1.2) +   
    labs(colour=NULL, x="Gestational Age", y="log(Relative Abundance)")
  

```

#Canonical Correlation Analysis (Figure 5)
```{r echo=FALSE}
library(mixOmics) #add pt/ft indicator 
cyto16S_df <- merge(cytoDcast,prop16S,by.x=c("KitID", "ParticipantID","VisitNum","true_ga", "trimester"),
                                      by.y=c("KitID", "PID", "VisitNum","true_ga","trimester"))

cyto16S_df <- cyto16S_df %>%
                 filter(!is.na(ethnicity)) %>%
                 group_by(ParticipantID,trimester) %>%
                 filter(VisitNum==min(VisitNum))

#Separate analysis for preterm/fullterm
by(cyto16S_df, cyto16S_df$ptft, function(x) {
  cca_cyto16S <- wrapper.sgcca(X=list(Cytokines=as.matrix(x[,8:16]), Bacteria=as.matrix(x[,28:ncol(x)])),
                                  ncomp=2,keepX = list(Cytokines=c(9,9),Bacteria=c(15,15)),scale=FALSE,near.zero.var=TRUE)

  VarExplained <- cca_cyto16S$explained_variance
  VarExplained
  
  varnames_Bacteria <- substr(cca_cyto16S$names$colnames$Bacteria,1,25)
  plotVar(cca_cyto16S, cex=c(3.5, 3.5), col=c("red","blue"), pch=c(16,17), var.names = list(cca_cyto16S$names$colnames$Cytokines, varnames_Bacteria))
  
})

```

